version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=personalblog.settings
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn personalblog.wsgi:application --bind 0.0.0.0:8000"

volumes:
  static_volume:
  media_volume:
